import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactQueryClientProvider } from "@/ReactQueryClientProvider";
import "./globals.css";
import { SideNavigation } from "./components/SideNavigation/SideNavigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryClientProvider>
          <SideNavigation>{children}</SideNavigation>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
